### ISSUE TITLE
Wait... Moose can sing?

### ISSUE THREAD

**Issue by daniel-hampton** [alex-anson/surprise-dan-after-1.0-drops#2]
https://github.com/alex-anson/surprise-dan-after-1.0-drops/blob/d9fa57c6ac390b9705b8cd0c6f698dc0b62b5b84/README.md?plain=1#L15

```
- youtube video of a moose song. or moose in the wild
```

This site really made my day. I can't help but smile.  :heart_eyes: 

But is there really a video out there of moose-song?! :musical_note: :notes: :musical_score: 

Feel free to close this =P

**Comment by alex-anson** [comment]
@dhampton084 
YAY! it had the intended effect, then 😁
Seriously can't thank you enough.

YT has everything you never wanted. 😆
https://www.youtube.com/watch?v=5_wqvGVhYxk
